global:
  scrape_interval:     15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:8000']

  - job_name: 'data-service'
    static_configs:
      - targets: ['data-service:8001']

  - job_name: 'feature-service'
    static_configs:
      - targets: ['feature-service:8002']

  - job_name: 'forecast-service'
    static_configs:
      - targets: ['forecast-service:8003']

  - job_name: 'optimization-service'
    static_configs:
      - targets: ['optimization-service:8004']

  - job_name: 'replenishment-service'
    static_configs:
      - targets: ['replenishment-service:8005']

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']

  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq:15672']
    metrics_path: /metrics
    params:
      auth_user: [admin]
      auth_pass: [admin]
